version: "3.0"

services:
  web:
    build:
      context: ./
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - ./src:/usr/src/app
    ports:
      - "3000:3000"
    command: bash -c "npm run dev"
    depends_on:
      - db
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: example
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf