version: "3.0"

services:
  web:
    build:
      context: ./
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - ./srcs:/usr/src/app
    ports:
      - "3000:3000"
    command: bash -c "npm run dev"
    depends_on:
      - db
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: example
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/initdb.d:/docker-entrypoint-initdb.d